name: Continuous integration

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]

jobs:
  server_test_job:
    name: API tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: server/ApiIntegrationTests/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Set up Google Cloud authentication
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/key.json
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
